### ISSUE TITLE
Broken spec: Topics behave like "notifiable in-app"

### ISSUE THREAD

**Issue by javierm** [AyuntamientoMadrid/consul#1626]
There's a broken spec which can be tested locally by running `rspec spec/features/topics_specs.rb:6`.

The reason why we never see the failures is that file is ignored by RSpec because it's named `topics_specs.rb`, while its name should be `topics_spec.rb`.

AFAIK these specs have always failed.
```
Failures:

  1) Topics Concerns behaves like notifiable in-app Author commented on his own notifiable
     Failure/Error: nested_path_for(resource) || url_for([resource, only_path: true])

     NoMethodError:
       undefined method `topic_url' for #<RSpec::ExampleGroups::Topics::Concerns::BehavesLikeNotifiableInApp:0x00565129f28728>
     Shared Example Group: "notifiable in-app" called from ./spec/features/topics_specs.rb:6
     # ./spec/support/common_actions/notifications.rb:35:in `path_for'
     # ./spec/shared/features/notifiable_in_app.rb:103:in `block (2 levels) in <top (required)>'

  2) Topics Concerns behaves like notifiable in-app Multiple replies to my comment
     Failure/Error: nested_path_for(resource) || url_for([resource, only_path: true])

     NoMethodError:
       undefined method `topic_url' for #<RSpec::ExampleGroups::Topics::Concerns::BehavesLikeNotifiableInApp:0x005651272cfbe0>
     Shared Example Group: "notifiable in-app" called from ./spec/features/topics_specs.rb:6
     # ./spec/support/common_actions/notifications.rb:35:in `path_for'
     # ./spec/shared/features/notifiable_in_app.rb:79:in `block (3 levels) in <top (required)>'
     # ./spec/shared/features/notifiable_in_app.rb:77:in `times'
     # ./spec/shared/features/notifiable_in_app.rb:77:in `block (2 levels) in <top (required)>'

  3) Topics Concerns behaves like notifiable in-app Author replied to his own comment
     Failure/Error: nested_path_for(resource) || url_for([resource, only_path: true])

     NoMethodError:
       undefined method `topic_url' for #<RSpec::ExampleGroups::Topics::Concerns::BehavesLikeNotifiableInApp:0x0056511f273988>
     Shared Example Group: "notifiable in-app" called from ./spec/features/topics_specs.rb:6
     # ./spec/support/common_actions/notifications.rb:35:in `path_for'
     # ./spec/shared/features/notifiable_in_app.rb:121:in `block (2 levels) in <top (required)>'

  4) Topics Concerns behaves like notifiable in-app A user replied to my comment
     Failure/Error: nested_path_for(resource) || url_for([resource, only_path: true])

     NoMethodError:
       undefined method `topic_url' for #<RSpec::ExampleGroups::Topics::Concerns::BehavesLikeNotifiableInApp:0x007fd3247ef780>
     Shared Example Group: "notifiable in-app" called from ./spec/features/topics_specs.rb:6
     # ./spec/support/common_actions/notifications.rb:35:in `path_for'
     # ./spec/shared/features/notifiable_in_app.rb:53:in `block (2 levels) in <top (required)>'

  5) Topics Concerns behaves like notifiable in-app Multiple users commented on my notifiable
     Failure/Error: nested_path_for(resource) || url_for([resource, only_path: true])

     NoMethodError:
       undefined method `topic_url' for #<RSpec::ExampleGroups::Topics::Concerns::BehavesLikeNotifiableInApp:0x007fd3242465b8>
     Shared Example Group: "notifiable in-app" called from ./spec/features/topics_specs.rb:6
     # ./spec/support/common_actions/notifications.rb:35:in `path_for'
     # ./spec/shared/features/notifiable_in_app.rb:31:in `block (3 levels) in <top (required)>'
     # ./spec/shared/features/notifiable_in_app.rb:28:in `times'
     # ./spec/shared/features/notifiable_in_app.rb:28:in `block (2 levels) in <top (required)>'

Finished in 17.35 seconds (files took 17.68 seconds to load)
7 examples, 5 failures

Failed examples:

rspec './spec/features/topics_specs.rb[1:1:1:6]' # Topics Concerns behaves like notifiable in-app Author commented on his own notifiable
rspec './spec/features/topics_specs.rb[1:1:1:5]' # Topics Concerns behaves like notifiable in-app Multiple replies to my comment
rspec './spec/features/topics_specs.rb[1:1:1:7]' # Topics Concerns behaves like notifiable in-app Author replied to his own comment
rspec './spec/features/topics_specs.rb[1:1:1:4]' # Topics Concerns behaves like notifiable in-app A user replied to my comment
rspec './spec/features/topics_specs.rb[1:1:1:3]' # Topics Concerns behaves like notifiable in-app Multiple users commented on my notifiable
```

**Comment by javierm** [comment]
It would be closed by consul#/3730.
